### ISSUE TITLE
'OSError: [Errno 2] No such file or directory' error when configuring WiFi using the Bluetooth-RPi mobile application

### ISSUE THREAD

**Issue by Drkstr** [ole-vi/bluetooth-server#4]
I have the bluetooth-server.py script running on my raspberry pi. I am having trouble configuring the WiFi on the pi using the Bluetooth-RPi mobile application. 

Here is the stack trace from the console. 
['{"SSID":"ssid","PWD":"password"}']
Traceback (most recent call last):
  File "/home/pi/projects/bluetooth_test/bluetooth_test.py", line 161, in <module>
    main()
  File "/home/pi/projects/bluetooth_test/bluetooth_test.py", line 132, in main
    shell, ble_comm, ble_line)
  File "/home/pi/projects/bluetooth_test/bluetooth_test.py", line 50, in readExecuteSend
    json_object['SSID'], json_object['PWD'])
  File "/home/pi/projects/bluetooth_test/bluetooth_test.py", line 72, in wifi_connect
    pirateship_wifi_output = subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

PS: I am not having issues with running commands,  only having issues with the wifi configuration

**Comment by i5o** [comment]
Hey @Drkstr we are no longer using this bluetooth server, we moved to
https://github.com/treehouses/control

which is the bluetooth server for the raspi and the app https://github.com/treehouses/remote
<sub><sup>`remote control`, see what we did there? :wink: </sub></sup>
Let me know if you need help with remote/control.

**Comment by Drkstr** [comment]
Ah, thanks man. Ill have a look at the other project :smiley: 

Might I suggest a quick note in the readme linking the treehouses project :smile_cat:
